feat: added repost endpoint
codewitgabi/full-featured-social-media-application-fastapi pull request #65
Opened 2024-09-06 16:40 UTC by izzyjosh

#### Related Issue (Link to issue ticket)
---

#64 

#### Description
---

Reposting or sharing a post which was posted by current or any other user

#### Context
---

​

#### How Has This Been Tested? Screenshots (if appropriate - Postman, etc)
---

- Pytest
![Screenshot_20240906-173522](https://github.com/user-attachments/assets/10d6f998-f2f9-40d1-b536-302ab48e5d92)
​

#### Types of changes
---

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
      ​

#### Checklist:
---

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-09-06 19:38 UTC, codewitgabi requested changes
Provide screenshot for actual api call

2024-09-06 19:38 UTC, codewitgabi commented on alembic.ini
Why change this file?

2024-09-06 20:32 UTC, izzyjosh commented on alembic.ini
Nothing 😁

2024-09-06 23:46 UTC, izzyjosh commented
![Screenshot_20240906-073017](https://github.com/user-attachments/assets/2926b177-ac2d-46b6-8424-1d27f96c744d)

2024-09-07 23:20 UTC, codewitgabi approved these changes

2024-09-07 23:21 UTC, merged